services:
  - type: web
    name: g-shopping-backend
    env: node
    plan: free
    buildCommand: "npm install && npm run build:backend"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: "mongodb+srv://admin:admin123@ecom.vmovqav.mongodb.net/?retryWrites=true&w=majority&appName=Ecom"
      - key: JWT_SECRET
        value: "AAAAB3NzaC1yc2EAAAABJQAAAQB/nAmOjTmezNUDKYvEeIRf2YnwM9/uUG1d0BYsc8/tRtx+RGi7N2lUbp728MXGwdnL9od4cItzky/zVdLZE2cycOa18xBK9cOWmcKS0A8FYBxEQWJ/q9YVUgZbFKfYGaGQxsER+A0w/fX8ALuk78ktP31K69LcQgxIsl7rNzxsoOQKJ/CIxOGMMxczYTiEoLvQhapFQMs3FL96didKr/QbrfB1WT6s3838SEaXfgZvLef1YB2xmfhbT9OXFE3FXvh2UPBfN+ffE7iiayQf/2XR+8j4N4bW30DiPtOQLGUrH1y5X/rpNZNlWW2+jGIxqZtgWg7lTy3mXy5x836Sj/6L"
    autoDeploy: true

  - type: static
    name: g-shopping-frontend
    env: static
    buildCommand: "npm install && npm run build:frontend"
    staticPublishPath: g-shopping-fe/dist
